/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as HomeIndexImport } from './routes/home/index'

// Create/Update Routes

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home': typeof HomeIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}

export interface FileRoutesByTo {
  '/home': typeof HomeIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home/': typeof HomeIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/onboarding'
  id: '__root__' | '/home/' | '/onboarding/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home/",
        "/onboarding/"
      ]
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
